name: business_finance_management_apk
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.70.2
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  cloud_firestore: ^5.6.3
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  uuid: ^4.5.1
  equatable: ^2.0.7
  firebase_core: ^3.11.0
  expense_repository:
    path: packages/expense_repository/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
